import os
import torch
import torch.nn.functional as F
import numpy as np
from arithmetic_coder import SimpleFrequencyTable,BitOutputStream,ArithmeticDecoder,ArithmeticEncoder,BitInputStream
from pym_transformer import PymTransformer
from tqdm import tqdm

# ── constants ──────────────────────────────────────────────────────────────────

DEVICE     = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
SCALE      = 1_000_000      # float prob → integer frequency
BLOCK_SIZE = 256            # bytes generated per block
SEED_LEN   = 256            # length of static seed
TOK_A      = 257            # first and last token of seed
TOK_B      = 256            # middle tokens of seed


# ── seed ───────────────────────────────────────────────────────────────────────

def make_seed():
    """
    Fixed static seed — known to both compressor and decompressor.
    Never transmitted. Always:
        [256, 257, 257, 257 ... 257, 256]
         ↑                           ↑
        pos 0                      pos 255
        middle 254 positions are all 257
    """
    seed = [TOK_B] * SEED_LEN
    seed[0]  = TOK_A
    seed[-1] = TOK_A
    return seed


# ── model ──────────────────────────────────────────────────────────────────────

def load_model(model_path, vocab_size=258, hidden_dim=256,
               num_layers=2, sequence_length=256):
    model = PymTransformer(
        vocab_size=vocab_size,
        hidden_dim=hidden_dim,
        num_layers=num_layers,
        sequence_length=sequence_length
    ).to(DEVICE)
    model.load_state_dict(torch.load(model_path, map_location=DEVICE))
    model.eval()
    return model


# ── probability helper ─────────────────────────────────────────────────────────

def get_freqs(model, context, vocab_size):
    """
    Run model on current context, return integer frequency table
    for arithmetic coder.
    context is a plain Python list of token ids.
    """
    inp = torch.tensor(context, dtype=torch.long).unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        logits, _ = model(inp)
        # prediction for the NEXT token is at the last position
        probs = F.softmax(logits[0, -1, :], dim=-1).float()

    freqs = (probs.cpu().numpy() * SCALE).astype(int).clip(1)
    return SimpleFrequencyTable(freqs.tolist())


# ── compress ───────────────────────────────────────────────────────────────────

def compress(model, byte_ids, output_path, vocab_size=258):
    """
    Encode every byte of the file into the arithmetic coded stream.

    Block structure:
        seed = [256, 257...257, 256]   (fixed, 256 tokens, never transmitted)
        model autoregressively predicts BLOCK_SIZE bytes
        those bytes are the next BLOCK_SIZE bytes of the file
        take those BLOCK_SIZE bytes as new seed
        repeat

    The arithmetic coder encodes each true byte using the model's
    predicted probability distribution at that position.
    """
    num_bytes   = len(byte_ids)
    num_blocks  = (num_bytes + BLOCK_SIZE - 1) // BLOCK_SIZE
    print(f"compressing  : {num_bytes:,} bytes")
    print(f"blocks       : {num_blocks:,}  ({BLOCK_SIZE} bytes each)")

    with open(output_path, 'wb') as f:
        bitout = BitOutputStream(f)
        enc    = ArithmeticEncoder(32, bitout)

        for block_idx in tqdm(range(num_blocks), desc="compress", unit="block"):
            # ── seed for this block ──
            if block_idx == 0:
                context = make_seed()
            else:
                # previous block's generated bytes become new seed
                prev_start = (block_idx - 1) * BLOCK_SIZE
                prev_end   = prev_start + BLOCK_SIZE
                context    = list(byte_ids[prev_start:prev_end])

                # pad with TOK_B if previous block was short (last block edge case)
                while len(context) < SEED_LEN:
                    context.append(TOK_B)

            # ── autoregressively encode this block ──
            block_start = block_idx * BLOCK_SIZE
            block_end   = min(block_start + BLOCK_SIZE, num_bytes)

            for pos in range(block_start, block_end):
                true_byte = byte_ids[pos]

                # model predicts next token given current context
                freqs = get_freqs(model, context, vocab_size)

                # encode true byte using model's prediction
                enc.write(freqs, true_byte)

                # append true byte to context for next prediction
                context.append(true_byte)

            # if block_idx % 100 == 0:
            #     pct = block_idx / num_blocks * 100
            #     print(f"  block {block_idx:,}/{num_blocks:,}  ({pct:.1f}%)", end='\r')

        enc.finish()
        bitout.close()

    print(f"\nwrote → {output_path}")


# ── decompress ─────────────────────────────────────────────────────────────────

def decompress(model, compressed_path, num_bytes, output_path, vocab_size=258):
    """
    Mirror image of compress. Both sides run identical model on identical
    context at every step so probability distributions always match.
    """
    num_blocks = (num_bytes + BLOCK_SIZE - 1) // BLOCK_SIZE
    print(f"decompressing: {num_bytes:,} bytes")
    print(f"blocks       : {num_blocks:,}")

    all_bytes = []

    with open(compressed_path, 'rb') as f:
        bitin = BitInputStream(f)
        dec   = ArithmeticDecoder(32, bitin)

        for block_idx in tqdm(range(num_blocks), desc="decompress", unit="block"):
            # ── same seed logic as compressor ──
            if block_idx == 0:
                context = make_seed()
            else:
                prev_start = (block_idx - 1) * BLOCK_SIZE
                prev_end   = prev_start + BLOCK_SIZE
                context    = list(all_bytes[prev_start:prev_end])

                while len(context) < SEED_LEN:
                    context.append(TOK_B)

            # ── autoregressively decode this block ──
            block_start = block_idx * BLOCK_SIZE
            block_end   = min(block_start + BLOCK_SIZE, num_bytes)

            for pos in range(block_start, block_end):
                # same model, same context → same probability distribution
                freqs = get_freqs(model, context, vocab_size)

                # decode using that distribution
                byte_val = dec.read(freqs)
                all_bytes.append(byte_val)
                context.append(byte_val)

            if block_idx % 100 == 0:
                pct = block_idx / num_blocks * 100
                print(f"  block {block_idx:,}/{num_blocks:,}  ({pct:.1f}%)", end='\r')

        bitin.close()

    with open(output_path, 'wb') as f:
        f.write(bytes(all_bytes))

    print(f"\nwrote → {output_path}")
    return all_bytes


# ── verify ─────────────────────────────────────────────────────────────────────

def verify(original_path, reconstructed_path):
    with open(original_path, 'rb') as f:
        original = f.read()
    with open(reconstructed_path, 'rb') as f:
        reconstructed = f.read()

    if original == reconstructed:
        print("lossless      : TRUE ✓")
        return True
    else:
        for i, (a, b) in enumerate(zip(original, reconstructed)):
            if a != b:
                print(f"lossless      : FALSE ✗  first mismatch at byte {i:,}")
                print(f"  expected {a} got {b}")
                break
        return False


# ── entry point ────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    INPUT_FILE      = 'test.txt'
    COMPRESSED_FILE = 'test.pym'
    RECONSTRUCTED   = 'test.reconstructed.txt'
    MODEL_PATH      = 'models/pym_particles.pt'
    VOCAB_SIZE      = 258

    # test on first 50KB only — correctness check before full run
    TEST_BYTES = 100 * 1024 * 1024

    print("loading model...")
    model    = load_model(MODEL_PATH, vocab_size=VOCAB_SIZE)

    with open(INPUT_FILE, 'rb') as f:
        byte_ids = list(f.read()[:TEST_BYTES])

    num_bytes    = len(byte_ids)
    original_mb  = num_bytes / 1024 / 1024
    print(f"testing on   : {original_mb:.3f} MB  ({num_bytes:,} bytes)")

    # ── compress ──
    compress(model, byte_ids, COMPRESSED_FILE, VOCAB_SIZE)

    compressed_mb = os.path.getsize(COMPRESSED_FILE) / 1024 / 1024
    bits_per_byte = compressed_mb * 8 / original_mb
    print(f"original     : {original_mb:.3f} MB")
    print(f"compressed   : {compressed_mb:.3f} MB")
    print(f"ratio        : {original_mb / compressed_mb:.2f}x")
    print(f"bits/byte    : {bits_per_byte:.3f}")

    # ── decompress ──
    decompress(model, COMPRESSED_FILE, num_bytes, RECONSTRUCTED, VOCAB_SIZE)

    # ── verify ──
    with open(INPUT_FILE, 'rb') as f:
        original_slice = f.read()[:TEST_BYTES]
    with open(RECONSTRUCTED, 'rb') as f:
        reconstructed = f.read()

    if original_slice == reconstructed:
        print("lossless      : TRUE ✓")
        print("\narchitecture works — scale up to full file when ready")
    else:
        for i, (a, b) in enumerate(zip(original_slice, reconstructed)):
            if a != b:
                print(f"lossless      : FALSE ✗  first mismatch at byte {i:,}")
                print(f"  expected {a} got {b}")
                break